[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mo"
version = "0.1.0"
description = "MO: Methodically organize CourseKata Data."
authors = ["Adam Blake <adam@ablake.dev>"]
license = "GPL-3.0-or-greater"
readme = "README.md"

[tool.poetry.scripts]
mo = "mo.cli.main:app"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.3.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.13"

[tool.ruff]
line-length = 100

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"packages/ckhub/tests/**/conftest.py" = ["F401", "F403"]

[tool.ruff.format]
skip-magic-trailing-comma = true
preview = true

[tool.ruff.isort]
known-first-party = ["dev", "ckhub", "tests"]
split-on-trailing-comma = false

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # Pyflakes
  "B",   # flake8-bugbear
  "SIM", # flake8-simplify
  "I",   # isort
  "UP",  # pyupgrade
]

[tool.ruff.extend-per-file-ignores]
"**/__init__.py" = ["F401"]
